//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by main. DO NOT EDIT.

package model

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewActionBuilder() *ActionBuilder {
	builder := &ActionBuilder{}
	builder.model = Action{}
	builder.functionref = NewFunctionRefBuilder()
	builder.eventref = NewEventRefBuilder()
	builder.subflowref = NewWorkflowRefBuilder()
	builder.sleep = NewSleepBuilder()
	builder.actiondatafilter = NewActionDataFilterBuilder()
	return builder
}

type ActionBuilder struct {
	model            Action
	functionref      *FunctionRefBuilder
	eventref         *EventRefBuilder
	subflowref       *WorkflowRefBuilder
	sleep            *SleepBuilder
	actiondatafilter *ActionDataFilterBuilder
}

func (b *ActionBuilder) ID(input string) {
	b.model.ID = input
}

func (b *ActionBuilder) Name(input string) {
	b.model.Name = input
}

func (b *ActionBuilder) FunctionRef() *FunctionRefBuilder {
	return b.functionref
}

func (b *ActionBuilder) EventRef() *EventRefBuilder {
	return b.eventref
}

func (b *ActionBuilder) SubFlowRef() *WorkflowRefBuilder {
	return b.subflowref
}

func (b *ActionBuilder) Sleep() *SleepBuilder {
	return b.sleep
}

func (b *ActionBuilder) RetryRef(input string) {
	b.model.RetryRef = input
}

func (b *ActionBuilder) NonRetryableErrors(input []string) {
	b.model.NonRetryableErrors = input
}

func (b *ActionBuilder) RetryableErrors(input []string) {
	b.model.RetryableErrors = input
}

func (b *ActionBuilder) ActionDataFilter() *ActionDataFilterBuilder {
	return b.actiondatafilter
}

func (b *ActionBuilder) Condition(input string) {
	b.model.Condition = input
}

func (b *ActionBuilder) Build() Action {
	functionref := b.functionref.Build()
	b.model.FunctionRef = &functionref
	eventref := b.eventref.Build()
	b.model.EventRef = &eventref
	subflowref := b.subflowref.Build()
	b.model.SubFlowRef = &subflowref
	sleep := b.sleep.Build()
	b.model.Sleep = &sleep
	b.model.ActionDataFilter = b.actiondatafilter.Build()
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewActionDataFilterBuilder() *ActionDataFilterBuilder {
	builder := &ActionDataFilterBuilder{}
	builder.model = ActionDataFilter{}
	return builder
}

type ActionDataFilterBuilder struct {
	model ActionDataFilter
}

func (b *ActionDataFilterBuilder) FromStateData(input string) {
	b.model.FromStateData = input
}

func (b *ActionDataFilterBuilder) UseResults(input bool) {
	b.model.UseResults = input
}

func (b *ActionDataFilterBuilder) Results(input string) {
	b.model.Results = input
}

func (b *ActionDataFilterBuilder) ToStateData(input string) {
	b.model.ToStateData = input
}

func (b *ActionDataFilterBuilder) Build() ActionDataFilter {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewAuthBuilder() *AuthBuilder {
	builder := &AuthBuilder{}
	builder.model = Auth{}
	builder.properties = NewAuthPropertiesBuilder()
	return builder
}

type AuthBuilder struct {
	model      Auth
	properties *AuthPropertiesBuilder
}

func (b *AuthBuilder) Name(input string) {
	b.model.Name = input
}

func (b *AuthBuilder) Scheme(input AuthType) {
	b.model.Scheme = input
}

func (b *AuthBuilder) Properties() *AuthPropertiesBuilder {
	return b.properties
}

func (b *AuthBuilder) Build() Auth {
	b.model.Properties = b.properties.Build()
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewAuthPropertiesBuilder() *AuthPropertiesBuilder {
	builder := &AuthPropertiesBuilder{}
	builder.model = AuthProperties{}
	builder.basic = NewBasicAuthPropertiesBuilder()
	builder.bearer = NewBearerAuthPropertiesBuilder()
	builder.oauth2 = NewOAuth2AuthPropertiesBuilder()
	return builder
}

type AuthPropertiesBuilder struct {
	model  AuthProperties
	basic  *BasicAuthPropertiesBuilder
	bearer *BearerAuthPropertiesBuilder
	oauth2 *OAuth2AuthPropertiesBuilder
}

func (b *AuthPropertiesBuilder) Basic() *BasicAuthPropertiesBuilder {
	return b.basic
}

func (b *AuthPropertiesBuilder) Bearer() *BearerAuthPropertiesBuilder {
	return b.bearer
}

func (b *AuthPropertiesBuilder) OAuth2() *OAuth2AuthPropertiesBuilder {
	return b.oauth2
}

func (b *AuthPropertiesBuilder) Build() AuthProperties {
	basic := b.basic.Build()
	b.model.Basic = &basic
	bearer := b.bearer.Build()
	b.model.Bearer = &bearer
	oauth2 := b.oauth2.Build()
	b.model.OAuth2 = &oauth2
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewAuthsBuilder() *AuthsBuilder {
	builder := &AuthsBuilder{}
	builder.model = Auths{}
	return builder
}

type AuthsBuilder struct {
	model Auths
}

func (b *AuthsBuilder) Build() Auths {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewBaseStateBuilder() *BaseStateBuilder {
	builder := &BaseStateBuilder{}
	builder.model = BaseState{}
	builder.onerrors = []*OnErrorBuilder{}
	builder.transition = NewTransitionBuilder()
	builder.statedatafilter = NewStateDataFilterBuilder()
	builder.end = NewEndBuilder()
	return builder
}

type BaseStateBuilder struct {
	model           BaseState
	onerrors        []*OnErrorBuilder
	transition      *TransitionBuilder
	statedatafilter *StateDataFilterBuilder
	end             *EndBuilder
}

func (b *BaseStateBuilder) ID(input string) {
	b.model.ID = input
}

func (b *BaseStateBuilder) Name(input string) {
	b.model.Name = input
}

func (b *BaseStateBuilder) Type(input StateType) {
	b.model.Type = input
}

func (b *BaseStateBuilder) AddOnError() *OnErrorBuilder {
	builder := NewOnErrorBuilder()
	b.onerrors = append(b.onerrors, builder)
	return builder
}

func (b *BaseStateBuilder) Transition() *TransitionBuilder {
	return b.transition
}

func (b *BaseStateBuilder) StateDataFilter() *StateDataFilterBuilder {
	return b.statedatafilter
}

func (b *BaseStateBuilder) CompensatedBy(input string) {
	b.model.CompensatedBy = input
}

func (b *BaseStateBuilder) UsedForCompensation(input bool) {
	b.model.UsedForCompensation = input
}

func (b *BaseStateBuilder) End() *EndBuilder {
	return b.end
}

func (b *BaseStateBuilder) Build() BaseState {
	b.model.OnErrors = []OnError{}
	for _, v := range b.onerrors {
		b.model.OnErrors = append(b.model.OnErrors, v.Build())
	}
	transition := b.transition.Build()
	b.model.Transition = &transition
	statedatafilter := b.statedatafilter.Build()
	b.model.StateDataFilter = &statedatafilter
	end := b.end.Build()
	b.model.End = &end
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewBaseWorkflowBuilder() *BaseWorkflowBuilder {
	builder := &BaseWorkflowBuilder{}
	builder.model = BaseWorkflow{}
	builder.start = NewStartBuilder()
	builder.datainputschema = NewDataInputSchemaBuilder()
	builder.constants = NewConstantsBuilder()
	builder.timeouts = NewTimeoutsBuilder()
	builder.errors = []*ErrorBuilder{}
	builder.auth = []*AuthBuilder{}
	return builder
}

type BaseWorkflowBuilder struct {
	model           BaseWorkflow
	start           *StartBuilder
	datainputschema *DataInputSchemaBuilder
	constants       *ConstantsBuilder
	timeouts        *TimeoutsBuilder
	errors          []*ErrorBuilder
	auth            []*AuthBuilder
}

func (b *BaseWorkflowBuilder) ID(input string) {
	b.model.ID = input
}

func (b *BaseWorkflowBuilder) Key(input string) {
	b.model.Key = input
}

func (b *BaseWorkflowBuilder) Name(input string) {
	b.model.Name = input
}

func (b *BaseWorkflowBuilder) Description(input string) {
	b.model.Description = input
}

func (b *BaseWorkflowBuilder) Version(input string) {
	b.model.Version = input
}

func (b *BaseWorkflowBuilder) Start() *StartBuilder {
	return b.start
}

func (b *BaseWorkflowBuilder) Annotations(input []string) {
	b.model.Annotations = input
}

func (b *BaseWorkflowBuilder) DataInputSchema() *DataInputSchemaBuilder {
	return b.datainputschema
}

func (b *BaseWorkflowBuilder) SpecVersion(input string) {
	b.model.SpecVersion = input
}

func (b *BaseWorkflowBuilder) Secrets(input Secrets) {
	b.model.Secrets = input
}

func (b *BaseWorkflowBuilder) Constants() *ConstantsBuilder {
	return b.constants
}

func (b *BaseWorkflowBuilder) ExpressionLang(input ExpressionLangType) {
	b.model.ExpressionLang = input
}

func (b *BaseWorkflowBuilder) Timeouts() *TimeoutsBuilder {
	return b.timeouts
}

func (b *BaseWorkflowBuilder) AddError() *ErrorBuilder {
	builder := NewErrorBuilder()
	b.errors = append(b.errors, builder)
	return builder
}

func (b *BaseWorkflowBuilder) KeepActive(input bool) {
	b.model.KeepActive = input
}

func (b *BaseWorkflowBuilder) AutoRetries(input bool) {
	b.model.AutoRetries = input
}

func (b *BaseWorkflowBuilder) AddAuth() *AuthBuilder {
	builder := NewAuthBuilder()
	b.auth = append(b.auth, builder)
	return builder
}

func (b *BaseWorkflowBuilder) Build() BaseWorkflow {
	start := b.start.Build()
	b.model.Start = &start
	datainputschema := b.datainputschema.Build()
	b.model.DataInputSchema = &datainputschema
	constants := b.constants.Build()
	b.model.Constants = &constants
	timeouts := b.timeouts.Build()
	b.model.Timeouts = &timeouts
	b.model.Errors = []Error{}
	for _, v := range b.errors {
		b.model.Errors = append(b.model.Errors, v.Build())
	}
	b.model.Auth = []Auth{}
	for _, v := range b.auth {
		b.model.Auth = append(b.model.Auth, v.Build())
	}
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewBasicAuthPropertiesBuilder() *BasicAuthPropertiesBuilder {
	builder := &BasicAuthPropertiesBuilder{}
	builder.model = BasicAuthProperties{}
	builder.common = NewCommonBuilder()
	return builder
}

type BasicAuthPropertiesBuilder struct {
	model  BasicAuthProperties
	common *CommonBuilder
}

func (b *BasicAuthPropertiesBuilder) Common() *CommonBuilder {
	return b.common
}

func (b *BasicAuthPropertiesBuilder) Secret(input string) {
	b.model.Secret = input
}

func (b *BasicAuthPropertiesBuilder) Username(input string) {
	b.model.Username = input
}

func (b *BasicAuthPropertiesBuilder) Password(input string) {
	b.model.Password = input
}

func (b *BasicAuthPropertiesBuilder) Build() BasicAuthProperties {
	b.model.Common = b.common.Build()
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewBearerAuthPropertiesBuilder() *BearerAuthPropertiesBuilder {
	builder := &BearerAuthPropertiesBuilder{}
	builder.model = BearerAuthProperties{}
	builder.common = NewCommonBuilder()
	return builder
}

type BearerAuthPropertiesBuilder struct {
	model  BearerAuthProperties
	common *CommonBuilder
}

func (b *BearerAuthPropertiesBuilder) Common() *CommonBuilder {
	return b.common
}

func (b *BearerAuthPropertiesBuilder) Secret(input string) {
	b.model.Secret = input
}

func (b *BearerAuthPropertiesBuilder) Token(input string) {
	b.model.Token = input
}

func (b *BearerAuthPropertiesBuilder) Build() BearerAuthProperties {
	b.model.Common = b.common.Build()
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewBranchBuilder() *BranchBuilder {
	builder := &BranchBuilder{}
	builder.model = Branch{}
	builder.actions = []*ActionBuilder{}
	builder.timeouts = NewBranchTimeoutsBuilder()
	return builder
}

type BranchBuilder struct {
	model    Branch
	actions  []*ActionBuilder
	timeouts *BranchTimeoutsBuilder
}

func (b *BranchBuilder) Name(input string) {
	b.model.Name = input
}

func (b *BranchBuilder) AddAction() *ActionBuilder {
	builder := NewActionBuilder()
	b.actions = append(b.actions, builder)
	return builder
}

func (b *BranchBuilder) Timeouts() *BranchTimeoutsBuilder {
	return b.timeouts
}

func (b *BranchBuilder) Build() Branch {
	b.model.Actions = []Action{}
	for _, v := range b.actions {
		b.model.Actions = append(b.model.Actions, v.Build())
	}
	timeouts := b.timeouts.Build()
	b.model.Timeouts = &timeouts
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewBranchTimeoutsBuilder() *BranchTimeoutsBuilder {
	builder := &BranchTimeoutsBuilder{}
	builder.model = BranchTimeouts{}
	return builder
}

type BranchTimeoutsBuilder struct {
	model BranchTimeouts
}

func (b *BranchTimeoutsBuilder) ActionExecTimeout(input string) {
	b.model.ActionExecTimeout = input
}

func (b *BranchTimeoutsBuilder) BranchExecTimeout(input string) {
	b.model.BranchExecTimeout = input
}

func (b *BranchTimeoutsBuilder) Build() BranchTimeouts {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewCallbackStateBuilder() *CallbackStateBuilder {
	builder := &CallbackStateBuilder{}
	builder.model = CallbackState{}
	builder.action = NewActionBuilder()
	builder.timeouts = NewCallbackStateTimeoutBuilder()
	builder.eventdatafilter = NewEventDataFilterBuilder()
	return builder
}

type CallbackStateBuilder struct {
	model           CallbackState
	action          *ActionBuilder
	timeouts        *CallbackStateTimeoutBuilder
	eventdatafilter *EventDataFilterBuilder
}

func (b *CallbackStateBuilder) Action() *ActionBuilder {
	return b.action
}

func (b *CallbackStateBuilder) EventRef(input string) {
	b.model.EventRef = input
}

func (b *CallbackStateBuilder) Timeouts() *CallbackStateTimeoutBuilder {
	return b.timeouts
}

func (b *CallbackStateBuilder) EventDataFilter() *EventDataFilterBuilder {
	return b.eventdatafilter
}

func (b *CallbackStateBuilder) Build() CallbackState {
	b.model.Action = b.action.Build()
	timeouts := b.timeouts.Build()
	b.model.Timeouts = &timeouts
	eventdatafilter := b.eventdatafilter.Build()
	b.model.EventDataFilter = &eventdatafilter
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewCallbackStateTimeoutBuilder() *CallbackStateTimeoutBuilder {
	builder := &CallbackStateTimeoutBuilder{}
	builder.model = CallbackStateTimeout{}
	builder.stateexectimeout = NewStateExecTimeoutBuilder()
	return builder
}

type CallbackStateTimeoutBuilder struct {
	model            CallbackStateTimeout
	stateexectimeout *StateExecTimeoutBuilder
}

func (b *CallbackStateTimeoutBuilder) StateExecTimeout() *StateExecTimeoutBuilder {
	return b.stateexectimeout
}

func (b *CallbackStateTimeoutBuilder) ActionExecTimeout(input string) {
	b.model.ActionExecTimeout = input
}

func (b *CallbackStateTimeoutBuilder) EventTimeout(input string) {
	b.model.EventTimeout = input
}

func (b *CallbackStateTimeoutBuilder) Build() CallbackStateTimeout {
	stateexectimeout := b.stateexectimeout.Build()
	b.model.StateExecTimeout = &stateexectimeout
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewCommonBuilder() *CommonBuilder {
	builder := &CommonBuilder{}
	builder.model = Common{}
	return builder
}

type CommonBuilder struct {
	model Common
}

func (b *CommonBuilder) Build() Common {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewConstantsBuilder() *ConstantsBuilder {
	builder := &ConstantsBuilder{}
	builder.model = Constants{}
	return builder
}

type ConstantsBuilder struct {
	model Constants
}

func (b *ConstantsBuilder) Build() Constants {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewConstantsDataBuilder() *ConstantsDataBuilder {
	builder := &ConstantsDataBuilder{}
	builder.model = ConstantsData{}
	return builder
}

type ConstantsDataBuilder struct {
	model ConstantsData
}

func (b *ConstantsDataBuilder) Build() ConstantsData {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewContinueAsBuilder() *ContinueAsBuilder {
	builder := &ContinueAsBuilder{}
	builder.model = ContinueAs{}
	builder.data = NewObjectBuilder()
	builder.workflowexectimeout = NewWorkflowExecTimeoutBuilder()
	return builder
}

type ContinueAsBuilder struct {
	model               ContinueAs
	data                *ObjectBuilder
	workflowexectimeout *WorkflowExecTimeoutBuilder
}

func (b *ContinueAsBuilder) WorkflowID(input string) {
	b.model.WorkflowID = input
}

func (b *ContinueAsBuilder) Version(input string) {
	b.model.Version = input
}

func (b *ContinueAsBuilder) Data() *ObjectBuilder {
	return b.data
}

func (b *ContinueAsBuilder) WorkflowExecTimeout() *WorkflowExecTimeoutBuilder {
	return b.workflowexectimeout
}

func (b *ContinueAsBuilder) Build() ContinueAs {
	b.model.Data = b.data.Build()
	b.model.WorkflowExecTimeout = b.workflowexectimeout.Build()
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewCorrelationBuilder() *CorrelationBuilder {
	builder := &CorrelationBuilder{}
	builder.model = Correlation{}
	return builder
}

type CorrelationBuilder struct {
	model Correlation
}

func (b *CorrelationBuilder) ContextAttributeName(input string) {
	b.model.ContextAttributeName = input
}

func (b *CorrelationBuilder) ContextAttributeValue(input string) {
	b.model.ContextAttributeValue = input
}

func (b *CorrelationBuilder) Build() Correlation {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewCronBuilder() *CronBuilder {
	builder := &CronBuilder{}
	builder.model = Cron{}
	return builder
}

type CronBuilder struct {
	model Cron
}

func (b *CronBuilder) Expression(input string) {
	b.model.Expression = input
}

func (b *CronBuilder) ValidUntil(input string) {
	b.model.ValidUntil = input
}

func (b *CronBuilder) Build() Cron {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewDataConditionBuilder() *DataConditionBuilder {
	builder := &DataConditionBuilder{}
	builder.model = DataCondition{}
	builder.end = NewEndBuilder()
	builder.transition = NewTransitionBuilder()
	return builder
}

type DataConditionBuilder struct {
	model      DataCondition
	end        *EndBuilder
	transition *TransitionBuilder
}

func (b *DataConditionBuilder) Name(input string) {
	b.model.Name = input
}

func (b *DataConditionBuilder) Condition(input string) {
	b.model.Condition = input
}

func (b *DataConditionBuilder) End() *EndBuilder {
	return b.end
}

func (b *DataConditionBuilder) Transition() *TransitionBuilder {
	return b.transition
}

func (b *DataConditionBuilder) Build() DataCondition {
	end := b.end.Build()
	b.model.End = &end
	transition := b.transition.Build()
	b.model.Transition = &transition
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewDataInputSchemaBuilder() *DataInputSchemaBuilder {
	builder := &DataInputSchemaBuilder{}
	builder.model = DataInputSchema{}
	return builder
}

type DataInputSchemaBuilder struct {
	model DataInputSchema
}

func (b *DataInputSchemaBuilder) Schema(input string) {
	b.model.Schema = input
}

func (b *DataInputSchemaBuilder) FailOnValidationErrors(input bool) {
	b.model.FailOnValidationErrors = input
}

func (b *DataInputSchemaBuilder) Build() DataInputSchema {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewDefaultConditionBuilder() *DefaultConditionBuilder {
	builder := &DefaultConditionBuilder{}
	builder.model = DefaultCondition{}
	builder.transition = NewTransitionBuilder()
	builder.end = NewEndBuilder()
	return builder
}

type DefaultConditionBuilder struct {
	model      DefaultCondition
	transition *TransitionBuilder
	end        *EndBuilder
}

func (b *DefaultConditionBuilder) Transition() *TransitionBuilder {
	return b.transition
}

func (b *DefaultConditionBuilder) End() *EndBuilder {
	return b.end
}

func (b *DefaultConditionBuilder) Build() DefaultCondition {
	transition := b.transition.Build()
	b.model.Transition = &transition
	end := b.end.Build()
	b.model.End = &end
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewDelayStateBuilder() *DelayStateBuilder {
	builder := &DelayStateBuilder{}
	builder.model = DelayState{}
	return builder
}

type DelayStateBuilder struct {
	model DelayState
}

func (b *DelayStateBuilder) TimeDelay(input string) {
	b.model.TimeDelay = input
}

func (b *DelayStateBuilder) Build() DelayState {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewEndBuilder() *EndBuilder {
	builder := &EndBuilder{}
	builder.model = End{}
	builder.produceevents = []*ProduceEventBuilder{}
	builder.continueas = NewContinueAsBuilder()
	return builder
}

type EndBuilder struct {
	model         End
	produceevents []*ProduceEventBuilder
	continueas    *ContinueAsBuilder
}

func (b *EndBuilder) Terminate(input bool) {
	b.model.Terminate = input
}

func (b *EndBuilder) AddProduceEvent() *ProduceEventBuilder {
	builder := NewProduceEventBuilder()
	b.produceevents = append(b.produceevents, builder)
	return builder
}

func (b *EndBuilder) Compensate(input bool) {
	b.model.Compensate = input
}

func (b *EndBuilder) ContinueAs() *ContinueAsBuilder {
	return b.continueas
}

func (b *EndBuilder) Build() End {
	b.model.ProduceEvents = []ProduceEvent{}
	for _, v := range b.produceevents {
		b.model.ProduceEvents = append(b.model.ProduceEvents, v.Build())
	}
	continueas := b.continueas.Build()
	b.model.ContinueAs = &continueas
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewErrorBuilder() *ErrorBuilder {
	builder := &ErrorBuilder{}
	builder.model = Error{}
	return builder
}

type ErrorBuilder struct {
	model Error
}

func (b *ErrorBuilder) Name(input string) {
	b.model.Name = input
}

func (b *ErrorBuilder) Code(input string) {
	b.model.Code = input
}

func (b *ErrorBuilder) Description(input string) {
	b.model.Description = input
}

func (b *ErrorBuilder) Build() Error {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewErrorsBuilder() *ErrorsBuilder {
	builder := &ErrorsBuilder{}
	builder.model = Errors{}
	return builder
}

type ErrorsBuilder struct {
	model Errors
}

func (b *ErrorsBuilder) Build() Errors {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewEventBuilder() *EventBuilder {
	builder := &EventBuilder{}
	builder.model = Event{}
	builder.common = NewCommonBuilder()
	builder.correlation = []*CorrelationBuilder{}
	return builder
}

type EventBuilder struct {
	model       Event
	common      *CommonBuilder
	correlation []*CorrelationBuilder
}

func (b *EventBuilder) Common() *CommonBuilder {
	return b.common
}

func (b *EventBuilder) Name(input string) {
	b.model.Name = input
}

func (b *EventBuilder) Source(input string) {
	b.model.Source = input
}

func (b *EventBuilder) Type(input string) {
	b.model.Type = input
}

func (b *EventBuilder) Kind(input EventKind) {
	b.model.Kind = input
}

func (b *EventBuilder) DataOnly(input bool) {
	b.model.DataOnly = input
}

func (b *EventBuilder) AddCorrelation() *CorrelationBuilder {
	builder := NewCorrelationBuilder()
	b.correlation = append(b.correlation, builder)
	return builder
}

func (b *EventBuilder) Build() Event {
	b.model.Common = b.common.Build()
	b.model.Correlation = []Correlation{}
	for _, v := range b.correlation {
		b.model.Correlation = append(b.model.Correlation, v.Build())
	}
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewEventConditionBuilder() *EventConditionBuilder {
	builder := &EventConditionBuilder{}
	builder.model = EventCondition{}
	builder.eventdatafilter = NewEventDataFilterBuilder()
	builder.end = NewEndBuilder()
	builder.transition = NewTransitionBuilder()
	return builder
}

type EventConditionBuilder struct {
	model           EventCondition
	eventdatafilter *EventDataFilterBuilder
	end             *EndBuilder
	transition      *TransitionBuilder
}

func (b *EventConditionBuilder) Name(input string) {
	b.model.Name = input
}

func (b *EventConditionBuilder) EventRef(input string) {
	b.model.EventRef = input
}

func (b *EventConditionBuilder) EventDataFilter() *EventDataFilterBuilder {
	return b.eventdatafilter
}

func (b *EventConditionBuilder) End() *EndBuilder {
	return b.end
}

func (b *EventConditionBuilder) Transition() *TransitionBuilder {
	return b.transition
}

func (b *EventConditionBuilder) Build() EventCondition {
	eventdatafilter := b.eventdatafilter.Build()
	b.model.EventDataFilter = &eventdatafilter
	end := b.end.Build()
	b.model.End = &end
	transition := b.transition.Build()
	b.model.Transition = &transition
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewEventConditionsBuilder() *EventConditionsBuilder {
	builder := &EventConditionsBuilder{}
	builder.model = EventConditions{}
	return builder
}

type EventConditionsBuilder struct {
	model EventConditions
}

func (b *EventConditionsBuilder) Build() EventConditions {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewEventDataFilterBuilder() *EventDataFilterBuilder {
	builder := &EventDataFilterBuilder{}
	builder.model = EventDataFilter{}
	return builder
}

type EventDataFilterBuilder struct {
	model EventDataFilter
}

func (b *EventDataFilterBuilder) UseData(input bool) {
	b.model.UseData = input
}

func (b *EventDataFilterBuilder) Data(input string) {
	b.model.Data = input
}

func (b *EventDataFilterBuilder) ToStateData(input string) {
	b.model.ToStateData = input
}

func (b *EventDataFilterBuilder) Build() EventDataFilter {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewEventRefBuilder() *EventRefBuilder {
	builder := &EventRefBuilder{}
	builder.model = EventRef{}
	builder.data = NewObjectBuilder()
	return builder
}

type EventRefBuilder struct {
	model EventRef
	data  *ObjectBuilder
}

func (b *EventRefBuilder) TriggerEventRef(input string) {
	b.model.TriggerEventRef = input
}

func (b *EventRefBuilder) ResultEventRef(input string) {
	b.model.ResultEventRef = input
}

func (b *EventRefBuilder) ResultEventTimeout(input string) {
	b.model.ResultEventTimeout = input
}

func (b *EventRefBuilder) Data() *ObjectBuilder {
	return b.data
}

func (b *EventRefBuilder) Invoke(input InvokeKind) {
	b.model.Invoke = input
}

func (b *EventRefBuilder) Build() EventRef {
	data := b.data.Build()
	b.model.Data = &data
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewEventStateBuilder() *EventStateBuilder {
	builder := &EventStateBuilder{}
	builder.model = EventState{}
	builder.onevents = []*OnEventsBuilder{}
	builder.timeouts = NewEventStateTimeoutBuilder()
	return builder
}

type EventStateBuilder struct {
	model    EventState
	onevents []*OnEventsBuilder
	timeouts *EventStateTimeoutBuilder
}

func (b *EventStateBuilder) Exclusive(input bool) {
	b.model.Exclusive = input
}

func (b *EventStateBuilder) AddOnEvents() *OnEventsBuilder {
	builder := NewOnEventsBuilder()
	b.onevents = append(b.onevents, builder)
	return builder
}

func (b *EventStateBuilder) Timeouts() *EventStateTimeoutBuilder {
	return b.timeouts
}

func (b *EventStateBuilder) Build() EventState {
	b.model.OnEvents = []OnEvents{}
	for _, v := range b.onevents {
		b.model.OnEvents = append(b.model.OnEvents, v.Build())
	}
	timeouts := b.timeouts.Build()
	b.model.Timeouts = &timeouts
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewEventStateTimeoutBuilder() *EventStateTimeoutBuilder {
	builder := &EventStateTimeoutBuilder{}
	builder.model = EventStateTimeout{}
	builder.stateexectimeout = NewStateExecTimeoutBuilder()
	return builder
}

type EventStateTimeoutBuilder struct {
	model            EventStateTimeout
	stateexectimeout *StateExecTimeoutBuilder
}

func (b *EventStateTimeoutBuilder) StateExecTimeout() *StateExecTimeoutBuilder {
	return b.stateexectimeout
}

func (b *EventStateTimeoutBuilder) ActionExecTimeout(input string) {
	b.model.ActionExecTimeout = input
}

func (b *EventStateTimeoutBuilder) EventTimeout(input string) {
	b.model.EventTimeout = input
}

func (b *EventStateTimeoutBuilder) Build() EventStateTimeout {
	stateexectimeout := b.stateexectimeout.Build()
	b.model.StateExecTimeout = &stateexectimeout
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewEventsBuilder() *EventsBuilder {
	builder := &EventsBuilder{}
	builder.model = Events{}
	return builder
}

type EventsBuilder struct {
	model Events
}

func (b *EventsBuilder) Build() Events {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewForEachStateBuilder() *ForEachStateBuilder {
	builder := &ForEachStateBuilder{}
	builder.model = ForEachState{}
	builder.actions = []*ActionBuilder{}
	builder.timeouts = NewForEachStateTimeoutBuilder()
	return builder
}

type ForEachStateBuilder struct {
	model    ForEachState
	actions  []*ActionBuilder
	timeouts *ForEachStateTimeoutBuilder
}

func (b *ForEachStateBuilder) InputCollection(input string) {
	b.model.InputCollection = input
}

func (b *ForEachStateBuilder) OutputCollection(input string) {
	b.model.OutputCollection = input
}

func (b *ForEachStateBuilder) IterationParam(input string) {
	b.model.IterationParam = input
}

func (b *ForEachStateBuilder) AddAction() *ActionBuilder {
	builder := NewActionBuilder()
	b.actions = append(b.actions, builder)
	return builder
}

func (b *ForEachStateBuilder) Timeouts() *ForEachStateTimeoutBuilder {
	return b.timeouts
}

func (b *ForEachStateBuilder) Mode(input ForEachModeType) {
	b.model.Mode = input
}

func (b *ForEachStateBuilder) Build() ForEachState {
	b.model.Actions = []Action{}
	for _, v := range b.actions {
		b.model.Actions = append(b.model.Actions, v.Build())
	}
	timeouts := b.timeouts.Build()
	b.model.Timeouts = &timeouts
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewForEachStateTimeoutBuilder() *ForEachStateTimeoutBuilder {
	builder := &ForEachStateTimeoutBuilder{}
	builder.model = ForEachStateTimeout{}
	builder.stateexectimeout = NewStateExecTimeoutBuilder()
	return builder
}

type ForEachStateTimeoutBuilder struct {
	model            ForEachStateTimeout
	stateexectimeout *StateExecTimeoutBuilder
}

func (b *ForEachStateTimeoutBuilder) StateExecTimeout() *StateExecTimeoutBuilder {
	return b.stateexectimeout
}

func (b *ForEachStateTimeoutBuilder) ActionExecTimeout(input string) {
	b.model.ActionExecTimeout = input
}

func (b *ForEachStateTimeoutBuilder) Build() ForEachStateTimeout {
	stateexectimeout := b.stateexectimeout.Build()
	b.model.StateExecTimeout = &stateexectimeout
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewFunctionBuilder() *FunctionBuilder {
	builder := &FunctionBuilder{}
	builder.model = Function{}
	builder.common = NewCommonBuilder()
	return builder
}

type FunctionBuilder struct {
	model  Function
	common *CommonBuilder
}

func (b *FunctionBuilder) Common() *CommonBuilder {
	return b.common
}

func (b *FunctionBuilder) Name(input string) {
	b.model.Name = input
}

func (b *FunctionBuilder) Operation(input string) {
	b.model.Operation = input
}

func (b *FunctionBuilder) Type(input FunctionType) {
	b.model.Type = input
}

func (b *FunctionBuilder) AuthRef(input string) {
	b.model.AuthRef = input
}

func (b *FunctionBuilder) Build() Function {
	b.model.Common = b.common.Build()
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewFunctionRefBuilder() *FunctionRefBuilder {
	builder := &FunctionRefBuilder{}
	builder.model = FunctionRef{}
	return builder
}

type FunctionRefBuilder struct {
	model FunctionRef
}

func (b *FunctionRefBuilder) RefName(input string) {
	b.model.RefName = input
}

func (b *FunctionRefBuilder) SelectionSet(input string) {
	b.model.SelectionSet = input
}

func (b *FunctionRefBuilder) Invoke(input InvokeKind) {
	b.model.Invoke = input
}

func (b *FunctionRefBuilder) Build() FunctionRef {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewFunctionsBuilder() *FunctionsBuilder {
	builder := &FunctionsBuilder{}
	builder.model = Functions{}
	return builder
}

type FunctionsBuilder struct {
	model Functions
}

func (b *FunctionsBuilder) Build() Functions {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewInjectStateBuilder() *InjectStateBuilder {
	builder := &InjectStateBuilder{}
	builder.model = InjectState{}
	builder.timeouts = NewInjectStateTimeoutBuilder()
	return builder
}

type InjectStateBuilder struct {
	model    InjectState
	timeouts *InjectStateTimeoutBuilder
}

func (b *InjectStateBuilder) Timeouts() *InjectStateTimeoutBuilder {
	return b.timeouts
}

func (b *InjectStateBuilder) Build() InjectState {
	timeouts := b.timeouts.Build()
	b.model.Timeouts = &timeouts
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewInjectStateTimeoutBuilder() *InjectStateTimeoutBuilder {
	builder := &InjectStateTimeoutBuilder{}
	builder.model = InjectStateTimeout{}
	builder.stateexectimeout = NewStateExecTimeoutBuilder()
	return builder
}

type InjectStateTimeoutBuilder struct {
	model            InjectStateTimeout
	stateexectimeout *StateExecTimeoutBuilder
}

func (b *InjectStateTimeoutBuilder) StateExecTimeout() *StateExecTimeoutBuilder {
	return b.stateexectimeout
}

func (b *InjectStateTimeoutBuilder) Build() InjectStateTimeout {
	stateexectimeout := b.stateexectimeout.Build()
	b.model.StateExecTimeout = &stateexectimeout
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewMetadataBuilder() *MetadataBuilder {
	builder := &MetadataBuilder{}
	builder.model = Metadata{}
	return builder
}

type MetadataBuilder struct {
	model Metadata
}

func (b *MetadataBuilder) Build() Metadata {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewOAuth2AuthPropertiesBuilder() *OAuth2AuthPropertiesBuilder {
	builder := &OAuth2AuthPropertiesBuilder{}
	builder.model = OAuth2AuthProperties{}
	builder.common = NewCommonBuilder()
	return builder
}

type OAuth2AuthPropertiesBuilder struct {
	model  OAuth2AuthProperties
	common *CommonBuilder
}

func (b *OAuth2AuthPropertiesBuilder) Common() *CommonBuilder {
	return b.common
}

func (b *OAuth2AuthPropertiesBuilder) Secret(input string) {
	b.model.Secret = input
}

func (b *OAuth2AuthPropertiesBuilder) Authority(input string) {
	b.model.Authority = input
}

func (b *OAuth2AuthPropertiesBuilder) GrantType(input GrantType) {
	b.model.GrantType = input
}

func (b *OAuth2AuthPropertiesBuilder) ClientID(input string) {
	b.model.ClientID = input
}

func (b *OAuth2AuthPropertiesBuilder) ClientSecret(input string) {
	b.model.ClientSecret = input
}

func (b *OAuth2AuthPropertiesBuilder) Scopes(input []string) {
	b.model.Scopes = input
}

func (b *OAuth2AuthPropertiesBuilder) Username(input string) {
	b.model.Username = input
}

func (b *OAuth2AuthPropertiesBuilder) Password(input string) {
	b.model.Password = input
}

func (b *OAuth2AuthPropertiesBuilder) Audiences(input []string) {
	b.model.Audiences = input
}

func (b *OAuth2AuthPropertiesBuilder) SubjectToken(input string) {
	b.model.SubjectToken = input
}

func (b *OAuth2AuthPropertiesBuilder) RequestedSubject(input string) {
	b.model.RequestedSubject = input
}

func (b *OAuth2AuthPropertiesBuilder) RequestedIssuer(input string) {
	b.model.RequestedIssuer = input
}

func (b *OAuth2AuthPropertiesBuilder) Build() OAuth2AuthProperties {
	b.model.Common = b.common.Build()
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewObjectBuilder() *ObjectBuilder {
	builder := &ObjectBuilder{}
	builder.model = Object{}
	builder.slicevalue = []*ObjectBuilder{}
	return builder
}

type ObjectBuilder struct {
	model      Object
	slicevalue []*ObjectBuilder
}

func (b *ObjectBuilder) Type(input Type) {
	b.model.Type = input
}

func (b *ObjectBuilder) StringValue(input string) {
	b.model.StringValue = input
}

func (b *ObjectBuilder) IntValue(input int32) {
	b.model.IntValue = input
}

func (b *ObjectBuilder) FloatValue(input float64) {
	b.model.FloatValue = input
}

func (b *ObjectBuilder) AddObject() *ObjectBuilder {
	builder := NewObjectBuilder()
	b.slicevalue = append(b.slicevalue, builder)
	return builder
}

func (b *ObjectBuilder) BoolValue(input bool) {
	b.model.BoolValue = input
}

func (b *ObjectBuilder) Build() Object {
	b.model.SliceValue = []Object{}
	for _, v := range b.slicevalue {
		b.model.SliceValue = append(b.model.SliceValue, v.Build())
	}
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewOnErrorBuilder() *OnErrorBuilder {
	builder := &OnErrorBuilder{}
	builder.model = OnError{}
	builder.transition = NewTransitionBuilder()
	builder.end = NewEndBuilder()
	return builder
}

type OnErrorBuilder struct {
	model      OnError
	transition *TransitionBuilder
	end        *EndBuilder
}

func (b *OnErrorBuilder) ErrorRef(input string) {
	b.model.ErrorRef = input
}

func (b *OnErrorBuilder) ErrorRefs(input []string) {
	b.model.ErrorRefs = input
}

func (b *OnErrorBuilder) Transition() *TransitionBuilder {
	return b.transition
}

func (b *OnErrorBuilder) End() *EndBuilder {
	return b.end
}

func (b *OnErrorBuilder) Build() OnError {
	transition := b.transition.Build()
	b.model.Transition = &transition
	end := b.end.Build()
	b.model.End = &end
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewOnEventsBuilder() *OnEventsBuilder {
	builder := &OnEventsBuilder{}
	builder.model = OnEvents{}
	builder.actions = []*ActionBuilder{}
	builder.eventdatafilter = NewEventDataFilterBuilder()
	return builder
}

type OnEventsBuilder struct {
	model           OnEvents
	actions         []*ActionBuilder
	eventdatafilter *EventDataFilterBuilder
}

func (b *OnEventsBuilder) EventRefs(input []string) {
	b.model.EventRefs = input
}

func (b *OnEventsBuilder) ActionMode(input ActionMode) {
	b.model.ActionMode = input
}

func (b *OnEventsBuilder) AddAction() *ActionBuilder {
	builder := NewActionBuilder()
	b.actions = append(b.actions, builder)
	return builder
}

func (b *OnEventsBuilder) EventDataFilter() *EventDataFilterBuilder {
	return b.eventdatafilter
}

func (b *OnEventsBuilder) Build() OnEvents {
	b.model.Actions = []Action{}
	for _, v := range b.actions {
		b.model.Actions = append(b.model.Actions, v.Build())
	}
	b.model.EventDataFilter = b.eventdatafilter.Build()
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewOperationStateBuilder() *OperationStateBuilder {
	builder := &OperationStateBuilder{}
	builder.model = OperationState{}
	builder.actions = []*ActionBuilder{}
	builder.timeouts = NewOperationStateTimeoutBuilder()
	return builder
}

type OperationStateBuilder struct {
	model    OperationState
	actions  []*ActionBuilder
	timeouts *OperationStateTimeoutBuilder
}

func (b *OperationStateBuilder) ActionMode(input ActionMode) {
	b.model.ActionMode = input
}

func (b *OperationStateBuilder) AddAction() *ActionBuilder {
	builder := NewActionBuilder()
	b.actions = append(b.actions, builder)
	return builder
}

func (b *OperationStateBuilder) Timeouts() *OperationStateTimeoutBuilder {
	return b.timeouts
}

func (b *OperationStateBuilder) Build() OperationState {
	b.model.Actions = []Action{}
	for _, v := range b.actions {
		b.model.Actions = append(b.model.Actions, v.Build())
	}
	timeouts := b.timeouts.Build()
	b.model.Timeouts = &timeouts
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewOperationStateTimeoutBuilder() *OperationStateTimeoutBuilder {
	builder := &OperationStateTimeoutBuilder{}
	builder.model = OperationStateTimeout{}
	builder.stateexectimeout = NewStateExecTimeoutBuilder()
	return builder
}

type OperationStateTimeoutBuilder struct {
	model            OperationStateTimeout
	stateexectimeout *StateExecTimeoutBuilder
}

func (b *OperationStateTimeoutBuilder) StateExecTimeout() *StateExecTimeoutBuilder {
	return b.stateexectimeout
}

func (b *OperationStateTimeoutBuilder) ActionExecTimeout(input string) {
	b.model.ActionExecTimeout = input
}

func (b *OperationStateTimeoutBuilder) Build() OperationStateTimeout {
	stateexectimeout := b.stateexectimeout.Build()
	b.model.StateExecTimeout = &stateexectimeout
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewParallelStateBuilder() *ParallelStateBuilder {
	builder := &ParallelStateBuilder{}
	builder.model = ParallelState{}
	builder.branches = []*BranchBuilder{}
	builder.timeouts = NewParallelStateTimeoutBuilder()
	return builder
}

type ParallelStateBuilder struct {
	model    ParallelState
	branches []*BranchBuilder
	timeouts *ParallelStateTimeoutBuilder
}

func (b *ParallelStateBuilder) AddBranch() *BranchBuilder {
	builder := NewBranchBuilder()
	b.branches = append(b.branches, builder)
	return builder
}

func (b *ParallelStateBuilder) CompletionType(input CompletionType) {
	b.model.CompletionType = input
}

func (b *ParallelStateBuilder) Timeouts() *ParallelStateTimeoutBuilder {
	return b.timeouts
}

func (b *ParallelStateBuilder) Build() ParallelState {
	b.model.Branches = []Branch{}
	for _, v := range b.branches {
		b.model.Branches = append(b.model.Branches, v.Build())
	}
	timeouts := b.timeouts.Build()
	b.model.Timeouts = &timeouts
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewParallelStateTimeoutBuilder() *ParallelStateTimeoutBuilder {
	builder := &ParallelStateTimeoutBuilder{}
	builder.model = ParallelStateTimeout{}
	builder.stateexectimeout = NewStateExecTimeoutBuilder()
	return builder
}

type ParallelStateTimeoutBuilder struct {
	model            ParallelStateTimeout
	stateexectimeout *StateExecTimeoutBuilder
}

func (b *ParallelStateTimeoutBuilder) StateExecTimeout() *StateExecTimeoutBuilder {
	return b.stateexectimeout
}

func (b *ParallelStateTimeoutBuilder) BranchExecTimeout(input string) {
	b.model.BranchExecTimeout = input
}

func (b *ParallelStateTimeoutBuilder) Build() ParallelStateTimeout {
	stateexectimeout := b.stateexectimeout.Build()
	b.model.StateExecTimeout = &stateexectimeout
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewProduceEventBuilder() *ProduceEventBuilder {
	builder := &ProduceEventBuilder{}
	builder.model = ProduceEvent{}
	builder.data = NewObjectBuilder()
	return builder
}

type ProduceEventBuilder struct {
	model ProduceEvent
	data  *ObjectBuilder
}

func (b *ProduceEventBuilder) EventRef(input string) {
	b.model.EventRef = input
}

func (b *ProduceEventBuilder) Data() *ObjectBuilder {
	return b.data
}

func (b *ProduceEventBuilder) Build() ProduceEvent {
	b.model.Data = b.data.Build()
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewRetriesBuilder() *RetriesBuilder {
	builder := &RetriesBuilder{}
	builder.model = Retries{}
	return builder
}

type RetriesBuilder struct {
	model Retries
}

func (b *RetriesBuilder) Build() Retries {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewRetryBuilder() *RetryBuilder {
	builder := &RetryBuilder{}
	builder.model = Retry{}
	return builder
}

type RetryBuilder struct {
	model Retry
}

func (b *RetryBuilder) Name(input string) {
	b.model.Name = input
}

func (b *RetryBuilder) Delay(input string) {
	b.model.Delay = input
}

func (b *RetryBuilder) MaxDelay(input string) {
	b.model.MaxDelay = input
}

func (b *RetryBuilder) Increment(input string) {
	b.model.Increment = input
}

func (b *RetryBuilder) Build() Retry {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewScheduleBuilder() *ScheduleBuilder {
	builder := &ScheduleBuilder{}
	builder.model = Schedule{}
	builder.cron = NewCronBuilder()
	return builder
}

type ScheduleBuilder struct {
	model Schedule
	cron  *CronBuilder
}

func (b *ScheduleBuilder) Interval(input string) {
	b.model.Interval = input
}

func (b *ScheduleBuilder) Cron() *CronBuilder {
	return b.cron
}

func (b *ScheduleBuilder) Timezone(input string) {
	b.model.Timezone = input
}

func (b *ScheduleBuilder) Build() Schedule {
	cron := b.cron.Build()
	b.model.Cron = &cron
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewSecretsBuilder() *SecretsBuilder {
	builder := &SecretsBuilder{}
	builder.model = Secrets{}
	return builder
}

type SecretsBuilder struct {
	model Secrets
}

func (b *SecretsBuilder) Build() Secrets {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewSleepBuilder() *SleepBuilder {
	builder := &SleepBuilder{}
	builder.model = Sleep{}
	return builder
}

type SleepBuilder struct {
	model Sleep
}

func (b *SleepBuilder) Before(input string) {
	b.model.Before = input
}

func (b *SleepBuilder) After(input string) {
	b.model.After = input
}

func (b *SleepBuilder) Build() Sleep {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewSleepStateBuilder() *SleepStateBuilder {
	builder := &SleepStateBuilder{}
	builder.model = SleepState{}
	builder.timeouts = NewSleepStateTimeoutBuilder()
	return builder
}

type SleepStateBuilder struct {
	model    SleepState
	timeouts *SleepStateTimeoutBuilder
}

func (b *SleepStateBuilder) Duration(input string) {
	b.model.Duration = input
}

func (b *SleepStateBuilder) Timeouts() *SleepStateTimeoutBuilder {
	return b.timeouts
}

func (b *SleepStateBuilder) Build() SleepState {
	timeouts := b.timeouts.Build()
	b.model.Timeouts = &timeouts
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewSleepStateTimeoutBuilder() *SleepStateTimeoutBuilder {
	builder := &SleepStateTimeoutBuilder{}
	builder.model = SleepStateTimeout{}
	builder.stateexectimeout = NewStateExecTimeoutBuilder()
	return builder
}

type SleepStateTimeoutBuilder struct {
	model            SleepStateTimeout
	stateexectimeout *StateExecTimeoutBuilder
}

func (b *SleepStateTimeoutBuilder) StateExecTimeout() *StateExecTimeoutBuilder {
	return b.stateexectimeout
}

func (b *SleepStateTimeoutBuilder) Build() SleepStateTimeout {
	stateexectimeout := b.stateexectimeout.Build()
	b.model.StateExecTimeout = &stateexectimeout
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewStartBuilder() *StartBuilder {
	builder := &StartBuilder{}
	builder.model = Start{}
	builder.schedule = NewScheduleBuilder()
	return builder
}

type StartBuilder struct {
	model    Start
	schedule *ScheduleBuilder
}

func (b *StartBuilder) StateName(input string) {
	b.model.StateName = input
}

func (b *StartBuilder) Schedule() *ScheduleBuilder {
	return b.schedule
}

func (b *StartBuilder) Build() Start {
	schedule := b.schedule.Build()
	b.model.Schedule = &schedule
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewStateBuilder() *StateBuilder {
	builder := &StateBuilder{}
	builder.model = State{}
	builder.basestate = NewBaseStateBuilder()
	builder.delaystate = NewDelayStateBuilder()
	builder.eventstate = NewEventStateBuilder()
	builder.operationstate = NewOperationStateBuilder()
	builder.parallelstate = NewParallelStateBuilder()
	builder.switchstate = NewSwitchStateBuilder()
	builder.foreachstate = NewForEachStateBuilder()
	builder.injectstate = NewInjectStateBuilder()
	builder.callbackstate = NewCallbackStateBuilder()
	builder.sleepstate = NewSleepStateBuilder()
	return builder
}

type StateBuilder struct {
	model          State
	basestate      *BaseStateBuilder
	delaystate     *DelayStateBuilder
	eventstate     *EventStateBuilder
	operationstate *OperationStateBuilder
	parallelstate  *ParallelStateBuilder
	switchstate    *SwitchStateBuilder
	foreachstate   *ForEachStateBuilder
	injectstate    *InjectStateBuilder
	callbackstate  *CallbackStateBuilder
	sleepstate     *SleepStateBuilder
}

func (b *StateBuilder) BaseState() *BaseStateBuilder {
	return b.basestate
}

func (b *StateBuilder) DelayState() *DelayStateBuilder {
	return b.delaystate
}

func (b *StateBuilder) EventState() *EventStateBuilder {
	return b.eventstate
}

func (b *StateBuilder) OperationState() *OperationStateBuilder {
	return b.operationstate
}

func (b *StateBuilder) ParallelState() *ParallelStateBuilder {
	return b.parallelstate
}

func (b *StateBuilder) SwitchState() *SwitchStateBuilder {
	return b.switchstate
}

func (b *StateBuilder) ForEachState() *ForEachStateBuilder {
	return b.foreachstate
}

func (b *StateBuilder) InjectState() *InjectStateBuilder {
	return b.injectstate
}

func (b *StateBuilder) CallbackState() *CallbackStateBuilder {
	return b.callbackstate
}

func (b *StateBuilder) SleepState() *SleepStateBuilder {
	return b.sleepstate
}

func (b *StateBuilder) Build() State {
	b.model.BaseState = b.basestate.Build()
	delaystate := b.delaystate.Build()
	b.model.DelayState = &delaystate
	eventstate := b.eventstate.Build()
	b.model.EventState = &eventstate
	operationstate := b.operationstate.Build()
	b.model.OperationState = &operationstate
	parallelstate := b.parallelstate.Build()
	b.model.ParallelState = &parallelstate
	switchstate := b.switchstate.Build()
	b.model.SwitchState = &switchstate
	foreachstate := b.foreachstate.Build()
	b.model.ForEachState = &foreachstate
	injectstate := b.injectstate.Build()
	b.model.InjectState = &injectstate
	callbackstate := b.callbackstate.Build()
	b.model.CallbackState = &callbackstate
	sleepstate := b.sleepstate.Build()
	b.model.SleepState = &sleepstate
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewStateDataFilterBuilder() *StateDataFilterBuilder {
	builder := &StateDataFilterBuilder{}
	builder.model = StateDataFilter{}
	return builder
}

type StateDataFilterBuilder struct {
	model StateDataFilter
}

func (b *StateDataFilterBuilder) Input(input string) {
	b.model.Input = input
}

func (b *StateDataFilterBuilder) Output(input string) {
	b.model.Output = input
}

func (b *StateDataFilterBuilder) Build() StateDataFilter {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewStateExecTimeoutBuilder() *StateExecTimeoutBuilder {
	builder := &StateExecTimeoutBuilder{}
	builder.model = StateExecTimeout{}
	return builder
}

type StateExecTimeoutBuilder struct {
	model StateExecTimeout
}

func (b *StateExecTimeoutBuilder) Single(input string) {
	b.model.Single = input
}

func (b *StateExecTimeoutBuilder) Total(input string) {
	b.model.Total = input
}

func (b *StateExecTimeoutBuilder) Build() StateExecTimeout {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewStatesBuilder() *StatesBuilder {
	builder := &StatesBuilder{}
	builder.model = States{}
	return builder
}

type StatesBuilder struct {
	model States
}

func (b *StatesBuilder) Build() States {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewSwitchStateBuilder() *SwitchStateBuilder {
	builder := &SwitchStateBuilder{}
	builder.model = SwitchState{}
	builder.defaultcondition = NewDefaultConditionBuilder()
	builder.eventconditions = []*EventConditionBuilder{}
	builder.dataconditions = []*DataConditionBuilder{}
	builder.timeouts = NewSwitchStateTimeoutBuilder()
	return builder
}

type SwitchStateBuilder struct {
	model            SwitchState
	defaultcondition *DefaultConditionBuilder
	eventconditions  []*EventConditionBuilder
	dataconditions   []*DataConditionBuilder
	timeouts         *SwitchStateTimeoutBuilder
}

func (b *SwitchStateBuilder) DefaultCondition() *DefaultConditionBuilder {
	return b.defaultcondition
}

func (b *SwitchStateBuilder) AddEventCondition() *EventConditionBuilder {
	builder := NewEventConditionBuilder()
	b.eventconditions = append(b.eventconditions, builder)
	return builder
}

func (b *SwitchStateBuilder) AddDataCondition() *DataConditionBuilder {
	builder := NewDataConditionBuilder()
	b.dataconditions = append(b.dataconditions, builder)
	return builder
}

func (b *SwitchStateBuilder) Timeouts() *SwitchStateTimeoutBuilder {
	return b.timeouts
}

func (b *SwitchStateBuilder) Build() SwitchState {
	b.model.DefaultCondition = b.defaultcondition.Build()
	b.model.EventConditions = []EventCondition{}
	for _, v := range b.eventconditions {
		b.model.EventConditions = append(b.model.EventConditions, v.Build())
	}
	b.model.DataConditions = []DataCondition{}
	for _, v := range b.dataconditions {
		b.model.DataConditions = append(b.model.DataConditions, v.Build())
	}
	timeouts := b.timeouts.Build()
	b.model.Timeouts = &timeouts
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewSwitchStateTimeoutBuilder() *SwitchStateTimeoutBuilder {
	builder := &SwitchStateTimeoutBuilder{}
	builder.model = SwitchStateTimeout{}
	builder.stateexectimeout = NewStateExecTimeoutBuilder()
	return builder
}

type SwitchStateTimeoutBuilder struct {
	model            SwitchStateTimeout
	stateexectimeout *StateExecTimeoutBuilder
}

func (b *SwitchStateTimeoutBuilder) StateExecTimeout() *StateExecTimeoutBuilder {
	return b.stateexectimeout
}

func (b *SwitchStateTimeoutBuilder) EventTimeout(input string) {
	b.model.EventTimeout = input
}

func (b *SwitchStateTimeoutBuilder) Build() SwitchStateTimeout {
	stateexectimeout := b.stateexectimeout.Build()
	b.model.StateExecTimeout = &stateexectimeout
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewTimeoutsBuilder() *TimeoutsBuilder {
	builder := &TimeoutsBuilder{}
	builder.model = Timeouts{}
	builder.workflowexectimeout = NewWorkflowExecTimeoutBuilder()
	builder.stateexectimeout = NewStateExecTimeoutBuilder()
	return builder
}

type TimeoutsBuilder struct {
	model               Timeouts
	workflowexectimeout *WorkflowExecTimeoutBuilder
	stateexectimeout    *StateExecTimeoutBuilder
}

func (b *TimeoutsBuilder) WorkflowExecTimeout() *WorkflowExecTimeoutBuilder {
	return b.workflowexectimeout
}

func (b *TimeoutsBuilder) StateExecTimeout() *StateExecTimeoutBuilder {
	return b.stateexectimeout
}

func (b *TimeoutsBuilder) ActionExecTimeout(input string) {
	b.model.ActionExecTimeout = input
}

func (b *TimeoutsBuilder) BranchExecTimeout(input string) {
	b.model.BranchExecTimeout = input
}

func (b *TimeoutsBuilder) EventTimeout(input string) {
	b.model.EventTimeout = input
}

func (b *TimeoutsBuilder) Build() Timeouts {
	workflowexectimeout := b.workflowexectimeout.Build()
	b.model.WorkflowExecTimeout = &workflowexectimeout
	stateexectimeout := b.stateexectimeout.Build()
	b.model.StateExecTimeout = &stateexectimeout
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewTransitionBuilder() *TransitionBuilder {
	builder := &TransitionBuilder{}
	builder.model = Transition{}
	builder.stateparent = NewStateBuilder()
	builder.produceevents = []*ProduceEventBuilder{}
	return builder
}

type TransitionBuilder struct {
	model         Transition
	stateparent   *StateBuilder
	produceevents []*ProduceEventBuilder
}

func (b *TransitionBuilder) stateParent() *StateBuilder {
	return b.stateparent
}

func (b *TransitionBuilder) NextState(input string) {
	b.model.NextState = input
}

func (b *TransitionBuilder) AddProduceEvent() *ProduceEventBuilder {
	builder := NewProduceEventBuilder()
	b.produceevents = append(b.produceevents, builder)
	return builder
}

func (b *TransitionBuilder) Compensate(input bool) {
	b.model.Compensate = input
}

func (b *TransitionBuilder) Build() Transition {
	stateparent := b.stateparent.Build()
	b.model.stateParent = &stateparent
	b.model.ProduceEvents = []ProduceEvent{}
	for _, v := range b.produceevents {
		b.model.ProduceEvents = append(b.model.ProduceEvents, v.Build())
	}
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewValidatorContextBuilder() *ValidatorContextBuilder {
	builder := &ValidatorContextBuilder{}
	builder.model = ValidatorContext{}
	return builder
}

type ValidatorContextBuilder struct {
	model ValidatorContext
}

func (b *ValidatorContextBuilder) Build() ValidatorContext {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewWorkflowBuilder() *WorkflowBuilder {
	builder := &WorkflowBuilder{}
	builder.model = Workflow{}
	builder.baseworkflow = NewBaseWorkflowBuilder()
	builder.states = []*StateBuilder{}
	builder.events = []*EventBuilder{}
	builder.functions = []*FunctionBuilder{}
	builder.retries = []*RetryBuilder{}
	return builder
}

type WorkflowBuilder struct {
	model        Workflow
	baseworkflow *BaseWorkflowBuilder
	states       []*StateBuilder
	events       []*EventBuilder
	functions    []*FunctionBuilder
	retries      []*RetryBuilder
}

func (b *WorkflowBuilder) BaseWorkflow() *BaseWorkflowBuilder {
	return b.baseworkflow
}

func (b *WorkflowBuilder) AddState() *StateBuilder {
	builder := NewStateBuilder()
	b.states = append(b.states, builder)
	return builder
}

func (b *WorkflowBuilder) AddEvent() *EventBuilder {
	builder := NewEventBuilder()
	b.events = append(b.events, builder)
	return builder
}

func (b *WorkflowBuilder) AddFunction() *FunctionBuilder {
	builder := NewFunctionBuilder()
	b.functions = append(b.functions, builder)
	return builder
}

func (b *WorkflowBuilder) AddRetry() *RetryBuilder {
	builder := NewRetryBuilder()
	b.retries = append(b.retries, builder)
	return builder
}

func (b *WorkflowBuilder) Build() Workflow {
	b.model.BaseWorkflow = b.baseworkflow.Build()
	b.model.States = []State{}
	for _, v := range b.states {
		b.model.States = append(b.model.States, v.Build())
	}
	b.model.Events = []Event{}
	for _, v := range b.events {
		b.model.Events = append(b.model.Events, v.Build())
	}
	b.model.Functions = []Function{}
	for _, v := range b.functions {
		b.model.Functions = append(b.model.Functions, v.Build())
	}
	b.model.Retries = []Retry{}
	for _, v := range b.retries {
		b.model.Retries = append(b.model.Retries, v.Build())
	}
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewWorkflowExecTimeoutBuilder() *WorkflowExecTimeoutBuilder {
	builder := &WorkflowExecTimeoutBuilder{}
	builder.model = WorkflowExecTimeout{}
	return builder
}

type WorkflowExecTimeoutBuilder struct {
	model WorkflowExecTimeout
}

func (b *WorkflowExecTimeoutBuilder) Duration(input string) {
	b.model.Duration = input
}

func (b *WorkflowExecTimeoutBuilder) Interrupt(input bool) {
	b.model.Interrupt = input
}

func (b *WorkflowExecTimeoutBuilder) RunBefore(input string) {
	b.model.RunBefore = input
}

func (b *WorkflowExecTimeoutBuilder) Build() WorkflowExecTimeout {
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewWorkflowRefBuilder() *WorkflowRefBuilder {
	builder := &WorkflowRefBuilder{}
	builder.model = WorkflowRef{}
	return builder
}

type WorkflowRefBuilder struct {
	model WorkflowRef
}

func (b *WorkflowRefBuilder) WorkflowID(input string) {
	b.model.WorkflowID = input
}

func (b *WorkflowRefBuilder) Version(input string) {
	b.model.Version = input
}

func (b *WorkflowRefBuilder) Invoke(input InvokeKind) {
	b.model.Invoke = input
}

func (b *WorkflowRefBuilder) OnParentComplete(input OnParentCompleteType) {
	b.model.OnParentComplete = input
}

func (b *WorkflowRefBuilder) Build() WorkflowRef {
	return b.model
}
