// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package model

// Serverless Workflow specification - common schema
type Common map[string]interface{}

// Metadata information
type Metadata map[string]interface{}

// Metadata information
type Metadata_1 map[string]interface{}
