# Copyright 2026 The Serverless Workflow Specification Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # -------------------------------------
  # Update Go modules
  # -------------------------------------
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "ricardozanini"
    assignees:
      - "ricardozanini"
    labels:
      - "dependencies"
      - "go"
    groups:
      go-minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # -------------------------------------
  # Update GitHub Actions workflows
  # -------------------------------------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "ricardozanini"
    assignees:
      - "ricardozanini"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions-minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
